#!/bin/bash
# Push file to sdcard
ARG=$1
adb connect 192.168.2.117:5555   #remove after status-check is implemented
chk=$(echo $1 |wc -w)
if [ ${chk} -ne 1 ]; then
    gdialog --title "Error" --msgbox "Only do one thing at a time, got ${chk}" 200 200
    exit 0
else
    which adb &>/dev/null
    if [ $? -ne 0 ]; then
        gdialog --title "Adb not found" --msgbox "Adb binary is not found, please install adb" 200 200
        exit 1
    fi
    gdialog --title "Finding device" --msgbox "Waiting for you device to become available to push $1, if not connected, do so now please." 200 200
    adb connect 192.168.2.117:5555
    #implement status-check here
    adb push $1 /sdcard/
    gdialog --title "Complete" --msgbox "$1 pushed to sdcard" 200 200
fi
